#!/bin/sh

create_devnode () {
	module=$1
	device=$1
	group="staff"
	mode="664"
   	major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
	if [ ! -z ${major} ]; then
		rm -f /dev/${device}
		mknod /dev/${device} c $major 0
		chgrp $group /dev/${device}
		chmod $mode /dev/${device}
	else
		echo "No device found in /proc/devices for driver \"${module}\""
	fi
}

delete_devnode () {
	device=$1
	rm -f /dev/${device}
}

case "$1" in
	start)
		echo "Loading ldd modules"
		insmod /lib/modules/$(uname -r)/extra/scull.ko || exit 1 
        insmod /lib/modules/$(uname -r)/extra/faulty.ko || exit 1 
		cd /lib/modules/$(uname -r)/extra && modprobe hello || exit 1
		echo "Creating device nodes"
		create_devnode scull
		create_devnode faulty
		;;
	stop)
		echo "Removing ldd modules"
		rmmod scull
        rmmod faulty
		rmmod hello
		echo "Deleting device nodes"
		delete_devnode faulty
		delete_devnode scull
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
		;;
esac

exit 0